version: '3'
services:
  neo-db:
    image: neo4j:5.3.0-community
    ports:
      - "7474:7474"
      - "7473:7473"
      - "7687:7687"
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/testtesttest
    volumes:
      - data:/data
      - logs:/logs

  process-article-service:
    build:
      context: .
    ports:
      - "1880:80"
    environment:
      - NEO4J_URI=neo4j://neo-db:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=testtesttest
      - NER_URL=http://localhost:8000
    depends_on:
      - neo-db
volumes:
  data:
  logs:
